### ISSUE TITLE
Question: Coverage Upload

### ISSUE THREAD

**Issue by hhslepicka** [tonybaloney/pytest-azurepipelines#17]
Thank you for this great plugin to pytest. It saves me a lot of work and the output is great! 
When you mention that the plugin executes the upload do you mean the upload to Azure or the upload to Codecov.io as well?

**Comment by tonybaloney** [comment]
Only to Azure

**Comment by hhslepicka** [comment]
Thank you, @tonybaloney ! I ended up figuring it out but forgot to close the issue.
