### ISSUE TITLE
[Feature Request] Ability to add attachments

### ISSUE THREAD

**Issue by j9ac9k** [tonybaloney/pytest-azurepipelines#21]
I just started using azure pipelines, so if this functionality is already present, but I don't see it, please feel free to disregard.

I'm working on the test suite for pyqtgraph, where we are interested in knowing what is rendered on the display when a test fails.  I have test code that grabs the window, and creates a png file.  I would love to be able to attach this file to a failed test, so it can be viewed in the attachment tab, but I'm not seeing a mechanism to do so.

Thanks for making the amazing extension.

**Comment by tonybaloney** [comment]
Is this a pytest plugin? How are you doing attachments at the moment? Does it just render them?

**Comment by tonybaloney** [comment]
Only TRX and NUnit3 seem to support this https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml#attachments-support

**Comment by j9ac9k** [comment]
I discovered that azure pipelines only supported attachments to those test formats a while back, I should have posted here, I apologise.

I'm good with closing out this issue as this is beyond the scope of this plugin

**Comment by tonybaloney** [comment]
See #35 :-)

**Comment by tonybaloney** [comment]
Released in 1.0.1
