### ISSUE TITLE
Option for not uploading code-coverage

### ISSUE THREAD

**Issue by shoyer** [tonybaloney/pytest-azurepipelines#27]
pytest-azurepipelines is very nice -- thanks for your work on it!

We are currently publishing test coverage to codecov.io, but not Azure, because I don't know how to merge coverage results across multiple runs: https://stackoverflow.com/questions/56776185

It is possible to add an option of some sort for disabling the warning about not uploading coverage? Right now, I see `##[warning]Coverage XML was not created, skipping upload.` in my logs.

**Comment by tonybaloney** [comment]
hi @shoyer the feature is supposed to just skip when coverage is not found.

I could certainly add a flag to disable this

**Comment by tonybaloney** [comment]
Added in #29

**Comment by shoyer** [comment]
Thanks @tonybaloney.

It might also make sense to use this option to disable setting the path for coverage xml output:
https://github.com/tonybaloney/pytest-azurepipelines/blob/508540fe79f0f8c15512baddb07a1d9dd1e7bff3/pytest_azurepipelines.py#L69

Or maybe pytest-azurepipelines could avoid changing this option at all, if it's already set?

I found it a little surprising that pytest-azurepipelines changed this, which turned out to mean that codecov.io couldn't find coverage results under the default path (`coverage.xml`):
https://github.com/pydata/xarray/pull/3085

**Comment by shoyer** [comment]
The codecov.io uploader actually hard-codes the name `coverage.xml`:
https://github.com/codecov/codecov-bash/blob/4678d212cce2078bbaaf5027af0c0dafaad6a095/codecov#L963

Unfortunately I couldn't figure out how override this option from pytest-azurepipelines, so for now I've had to remove it from my project to ensure we get test coverage.

**Comment by tonybaloney** [comment]
Thanks. I’m working on a release today so I’ll get this fixed

Anthony Shaw

________________________________

**Comment by tonybaloney** [comment]
released in 0.8.0
