### ISSUE TITLE
Feedback for 1.0.0rc3

### ISSUE THREAD

**Issue by canyon289** [tonybaloney/pytest-azurepipelines#46]
Hi, Saw the tweet below and wanted to help out. We created a branch that installs this release candidate.
https://twitter.com/anthonypjshaw/status/1270205981616529408

Our feedback is here. Hopefully this helps!
https://github.com/arviz-devs/arviz/pull/1230#issuecomment-641465208

https://github.com/arviz-devs/arviz/pull/1230

Feel free to close anytime since there's no real issue here. Thanks for the plugin

**Comment by tonybaloney** [comment]
thanks, this is really helpful actually. in the output, I can see that it didn't produce or upload any test results.

It did produce the coverage report files though.
