### ISSUE TITLE
{Question] Is this project abandoned?

### ISSUE THREAD

**Issue by fnrcum** [tonybaloney/pytest-azurepipelines#54]
I've seen many issues in the issues tab as well as PRs and people offering to fix things but no responses.

There's also been no real activity in the repo for 2 years so I am wondering if this is still maintained here and if it's still safe to use.

**Comment by tonybaloney** [comment]
still here :) its a 300-line script that has 200k downloads a month so I'm only touching things that are broken. I'll take another look at the backlog
